//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.25 at 07:33:34 PM EDT 
//


package me.kolek.fix.repository.xml;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for Field_cs_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Field_cs_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tag" type="{}Tag_t"/>
 *         &lt;element name="Name" type="{}SymbolicName_t"/>
 *         &lt;element name="Type" type="{}Datatype_t"/>
 *         &lt;element name="AssociatedDataTag" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AbbrName" type="{}SymbolicName_t" minOccurs="0"/>
 *         &lt;element name="BaseCategory" type="{}CategoryID_t" minOccurs="0"/>
 *         &lt;element name="BaseCategoryAbbrName" type="{}Name_t" minOccurs="0"/>
 *         &lt;element name="NotReqXML" type="{}BOOL_t"/>
 *         &lt;element name="EnumDatatype" type="{}Tag_t" minOccurs="0"/>
 *         &lt;element name="UnionDataType" type="{}UnionDataType_t" minOccurs="0"/>
 *         &lt;element name="Description" type="{}Description_t"/>
 *         &lt;element name="Elaboration" type="{}Elaboration_t" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}EntityLevelRevisionAttribGrp"/>
 *       &lt;attribute name="replaced" type="{}Version_t" />
 *       &lt;attribute name="replacedEP" type="{}EP_t" />
 *       &lt;attribute name="replacedByField" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="notUsed" type="{}BOOL_t" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Field_cs_t", propOrder = {
    "tag",
    "name",
    "type",
    "associatedDataTag",
    "abbrName",
    "baseCategory",
    "baseCategoryAbbrName",
    "notReqXML",
    "enumDatatype",
    "unionDataType",
    "description",
    "elaboration"
})
public class FieldCsT {

    @XmlElement(name = "Tag", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger tag;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "AssociatedDataTag")
    protected Integer associatedDataTag;
    @XmlElement(name = "AbbrName")
    protected String abbrName;
    @XmlElement(name = "BaseCategory")
    protected String baseCategory;
    @XmlElement(name = "BaseCategoryAbbrName")
    protected String baseCategoryAbbrName;
    @XmlElement(name = "NotReqXML")
    protected short notReqXML;
    @XmlElement(name = "EnumDatatype")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger enumDatatype;
    @XmlElement(name = "UnionDataType")
    @XmlSchemaType(name = "string")
    protected UnionDataTypeT unionDataType;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Elaboration")
    protected String elaboration;
    @XmlAttribute(name = "replaced")
    protected String replaced;
    @XmlAttribute(name = "replacedEP")
    protected BigInteger replacedEP;
    @XmlAttribute(name = "replacedByField")
    protected Integer replacedByField;
    @XmlAttribute(name = "notUsed")
    protected Short notUsed;
    @XmlAttribute(name = "added")
    protected String added;
    @XmlAttribute(name = "addedEP")
    protected BigInteger addedEP;
    @XmlAttribute(name = "deprecated")
    protected String deprecated;
    @XmlAttribute(name = "deprecatedEP")
    protected BigInteger deprecatedEP;
    @XmlAttribute(name = "issue")
    protected String issue;
    @XmlAttribute(name = "updated")
    protected String updated;
    @XmlAttribute(name = "updatedEP")
    protected BigInteger updatedEP;

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTag(BigInteger value) {
        this.tag = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the associatedDataTag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAssociatedDataTag() {
        return associatedDataTag;
    }

    /**
     * Sets the value of the associatedDataTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAssociatedDataTag(Integer value) {
        this.associatedDataTag = value;
    }

    /**
     * Gets the value of the abbrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbrName() {
        return abbrName;
    }

    /**
     * Sets the value of the abbrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbrName(String value) {
        this.abbrName = value;
    }

    /**
     * Gets the value of the baseCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCategory() {
        return baseCategory;
    }

    /**
     * Sets the value of the baseCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCategory(String value) {
        this.baseCategory = value;
    }

    /**
     * Gets the value of the baseCategoryAbbrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCategoryAbbrName() {
        return baseCategoryAbbrName;
    }

    /**
     * Sets the value of the baseCategoryAbbrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCategoryAbbrName(String value) {
        this.baseCategoryAbbrName = value;
    }

    /**
     * Gets the value of the notReqXML property.
     * 
     */
    public short getNotReqXML() {
        return notReqXML;
    }

    /**
     * Sets the value of the notReqXML property.
     * 
     */
    public void setNotReqXML(short value) {
        this.notReqXML = value;
    }

    /**
     * Gets the value of the enumDatatype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnumDatatype() {
        return enumDatatype;
    }

    /**
     * Sets the value of the enumDatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnumDatatype(BigInteger value) {
        this.enumDatatype = value;
    }

    /**
     * Gets the value of the unionDataType property.
     * 
     * @return
     *     possible object is
     *     {@link UnionDataTypeT }
     *     
     */
    public UnionDataTypeT getUnionDataType() {
        return unionDataType;
    }

    /**
     * Sets the value of the unionDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnionDataTypeT }
     *     
     */
    public void setUnionDataType(UnionDataTypeT value) {
        this.unionDataType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the elaboration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElaboration() {
        return elaboration;
    }

    /**
     * Sets the value of the elaboration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElaboration(String value) {
        this.elaboration = value;
    }

    /**
     * Gets the value of the replaced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaced() {
        return replaced;
    }

    /**
     * Sets the value of the replaced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaced(String value) {
        this.replaced = value;
    }

    /**
     * Gets the value of the replacedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplacedEP() {
        return replacedEP;
    }

    /**
     * Sets the value of the replacedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplacedEP(BigInteger value) {
        this.replacedEP = value;
    }

    /**
     * Gets the value of the replacedByField property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReplacedByField() {
        return replacedByField;
    }

    /**
     * Sets the value of the replacedByField property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReplacedByField(Integer value) {
        this.replacedByField = value;
    }

    /**
     * Gets the value of the notUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNotUsed() {
        return notUsed;
    }

    /**
     * Sets the value of the notUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNotUsed(Short value) {
        this.notUsed = value;
    }

    /**
     * Gets the value of the added property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdded() {
        return added;
    }

    /**
     * Sets the value of the added property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdded(String value) {
        this.added = value;
    }

    /**
     * Gets the value of the addedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddedEP() {
        return addedEP;
    }

    /**
     * Sets the value of the addedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddedEP(BigInteger value) {
        this.addedEP = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeprecated(String value) {
        this.deprecated = value;
    }

    /**
     * Gets the value of the deprecatedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDeprecatedEP() {
        return deprecatedEP;
    }

    /**
     * Sets the value of the deprecatedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDeprecatedEP(BigInteger value) {
        this.deprecatedEP = value;
    }

    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssue(String value) {
        this.issue = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(String value) {
        this.updated = value;
    }

    /**
     * Gets the value of the updatedEP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdatedEP() {
        return updatedEP;
    }

    /**
     * Sets the value of the updatedEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdatedEP(BigInteger value) {
        this.updatedEP = value;
    }

}
