//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.25 at 07:33:34 PM EDT 
//


package me.kolek.fix.repository.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the me.kolek.fix.repository package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: me.kolek.fix.repository
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link ComponentCsT }
     * 
     */
    public ComponentCsT createComponentCsT() {
        return new ComponentCsT();
    }

    /**
     * Create an instance of {@link Enums }
     * 
     */
    public Enums createEnums() {
        return new Enums();
    }

    /**
     * Create an instance of {@link EnumCsT }
     * 
     */
    public EnumCsT createEnumCsT() {
        return new EnumCsT();
    }

    /**
     * Create an instance of {@link MsgContents }
     * 
     */
    public MsgContents createMsgContents() {
        return new MsgContents();
    }

    /**
     * Create an instance of {@link MsgContentCsT }
     * 
     */
    public MsgContentCsT createMsgContentCsT() {
        return new MsgContentCsT();
    }

    /**
     * Create an instance of {@link Fields }
     * 
     */
    public Fields createFields() {
        return new Fields();
    }

    /**
     * Create an instance of {@link FieldCsT }
     * 
     */
    public FieldCsT createFieldCsT() {
        return new FieldCsT();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link MessageCsT }
     * 
     */
    public MessageCsT createMessageCsT() {
        return new MessageCsT();
    }

    /**
     * Create an instance of {@link Sections }
     * 
     */
    public Sections createSections() {
        return new Sections();
    }

    /**
     * Create an instance of {@link SectionCsT }
     * 
     */
    public SectionCsT createSectionCsT() {
        return new SectionCsT();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link CategoryCsT }
     * 
     */
    public CategoryCsT createCategoryCsT() {
        return new CategoryCsT();
    }

    /**
     * Create an instance of {@link Abbreviations }
     * 
     */
    public Abbreviations createAbbreviations() {
        return new Abbreviations();
    }

    /**
     * Create an instance of {@link AbbreviationCsT }
     * 
     */
    public AbbreviationCsT createAbbreviationCsT() {
        return new AbbreviationCsT();
    }

    /**
     * Create an instance of {@link Datatypes }
     * 
     */
    public Datatypes createDatatypes() {
        return new Datatypes();
    }

    /**
     * Create an instance of {@link DatatypeCsT }
     * 
     */
    public DatatypeCsT createDatatypeCsT() {
        return new DatatypeCsT();
    }

    /**
     * Create an instance of {@link DatatypeXMLT }
     * 
     */
    public DatatypeXMLT createDatatypeXMLT() {
        return new DatatypeXMLT();
    }

}
