//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.25 at 07:33:34 PM EDT 
//


package me.kolek.fix.repository.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SectionID_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SectionID_t"&gt;
 *   &lt;restriction base="{}Name_t"&gt;
 *     &lt;enumeration value="Session"/&gt;
 *     &lt;enumeration value="PreTrade"/&gt;
 *     &lt;enumeration value="Trade"/&gt;
 *     &lt;enumeration value="PostTrade"/&gt;
 *     &lt;enumeration value="Infrastructure"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SectionID_t")
@XmlEnum
public enum SectionIDT {

    @XmlEnumValue("Session")
    SESSION("Session"),
    @XmlEnumValue("PreTrade")
    PRE_TRADE("PreTrade"),
    @XmlEnumValue("Trade")
    TRADE("Trade"),
    @XmlEnumValue("PostTrade")
    POST_TRADE("PostTrade"),
    @XmlEnumValue("Infrastructure")
    INFRASTRUCTURE("Infrastructure"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    SectionIDT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SectionIDT fromValue(String v) {
        for (SectionIDT c: SectionIDT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
